### ISSUE TITLE
HOW TO: Change LLM models in this ?

### ISSUE THREAD

**Issue by NoobFullStack** [gsaivinay/awesome-chatbot#1]
Hi there, 

I've tried to adjust the LLM via the /pages/api/chat.ts; but I am unable to properly change the LLM to work with.. Can you provide a quick tip how to correctly do this in the repo?

**Comment by gsaivinay** [comment]
Hi @1NoobDev ,

Could you let me know which model you are trying to add?

Along with changing model name [here](https://github.com/gsaivinay/awesome-chatbot/blob/main/src/pages/api/chat.ts#L202), Need to check if config is present [here](https://github.com/gsaivinay/awesome-chatbot/blob/main/src/pages/api/chat.ts#L36) change the config variable [here](https://github.com/gsaivinay/awesome-chatbot/blob/main/src/pages/api/chat.ts#L184C15-L184C15) and make sure [this](https://github.com/gsaivinay/awesome-chatbot/blob/main/src/pages/api/chat.ts#L92) function can support that prompt format.

Let me know the model name and I might have a look.

**Comment by gsaivinay** [comment]
I've just added mixtral instruct as the default model. It should be better than the code llama 34b.
